// Per-language UI chrome strings for ChatInterface — single source of truth shared
// between mini_site's ChatWidget.astro (the 11 real site languages) and admin_client's
// AiChatPreview.jsx (the CMS live preview, which follows the page editor's own
// "Bewerkingstaal" language picker). Previously each consumer kept its own copy —
// mini_site's stayed correct, admin_client's was a single hardcoded Dutch table, so the
// CMS preview never matched the language actually selected. Centralizing here means
// both stay in sync automatically instead of drifting again.
export const CHAT_STRINGS = {
    nl: {
        title: 'Stel je vraag', inputLabel: 'Typ je vraag', send: 'Verstuur',
        startHint: 'Kies een onderwerp of stel een vraag hieronder',
        thinking: 'Aan het antwoorden…', error: 'Er ging iets mis. Probeer het opnieuw.',
        retry: 'Opnieuw proberen', relatedHelp: 'Gerelateerde hulp',
        call: 'Bellen', email: 'E-mailen', website: 'Website', route: 'Route', moreInfo: 'Meer info',
        openChat: 'Open chat', closeChat: 'Sluit chat', clearChat: 'Wis chat', clearInput: 'Wissen', you: 'Jij', assistant: 'Stappie',
        disclaimer: 'Dit is een AI-assistent. Controleer belangrijke informatie altijd bij de organisatie zelf.',
        languageName: 'Dutch',
        aboutYouTitle: 'Over jou (optioneel)', nameLabel: 'Hoe mogen we je noemen?', ageLabel: 'Wat is je leeftijd?',
        genderLabel: 'Wat is je geslacht?', intakeNotStored: 'Optioneel. Wordt niet opgeslagen.',
        loggingNotice: 'We kunnen dit gesprek gebruiken om onze dienstverlening te verbeteren.',
        loggingOptOutLink: 'Afmelden voor deze sessie',
        loggingOptOutModalTitle: 'Gesprek niet opslaan?',
        loggingOptOutModalBody: 'Hiermee stoppen we het opslaan van dit gesprek voor beoordeling, voor de rest van deze browsersessie. Je kunt de chat gewoon blijven gebruiken.',
        loggingOptOutConfirm: 'Uitschakelen voor deze sessie',
        loggingOptOutCancel: 'Annuleren',
        loggingOptedOutNotice: 'Opslaan is uitgeschakeld voor deze sessie.',
    },
    en: {
        title: 'Ask your question', inputLabel: 'Type your question', send: 'Send',
        startHint: 'Choose a topic or ask a question below',
        thinking: 'Thinking…', error: 'Something went wrong. Please try again.',
        retry: 'Try again', relatedHelp: 'Related help',
        call: 'Call', email: 'Email', website: 'Website', route: 'Directions', moreInfo: 'More info',
        openChat: 'Open chat', closeChat: 'Close chat', clearChat: 'Clear chat', clearInput: 'Clear', you: 'You', assistant: 'Stappie',
        disclaimer: 'This is an AI assistant. Always double-check important details with the organisation itself.',
        languageName: 'English',
        aboutYouTitle: 'About you (optional)', nameLabel: 'What should we call you?', ageLabel: 'Your age',
        genderLabel: 'Your gender', intakeNotStored: 'Optional. Never stored.',
        loggingNotice: 'We may use this conversation to help improve our services.',
        loggingOptOutLink: 'Opt out for this session',
        loggingOptOutModalTitle: 'Turn off conversation logging?',
        loggingOptOutModalBody: 'This stops us from saving this conversation for review, for the rest of this browser session. You can keep chatting as normal.',
        loggingOptOutConfirm: 'Turn off for this session',
        loggingOptOutCancel: 'Cancel',
        loggingOptedOutNotice: 'Logging is turned off for this session.',
    },
    ar: {
        title: 'اطرح سؤالك', inputLabel: 'اكتب سؤالك', send: 'إرسال',
        startHint: 'اختر موضوعًا أو اطرح سؤالاً أدناه',
        thinking: 'جارٍ الكتابة…', error: 'حدث خطأ ما. حاول مرة أخرى.',
        retry: 'حاول مرة أخرى', relatedHelp: 'مساعدة ذات صلة',
        call: 'اتصال', email: 'بريد إلكتروني', website: 'الموقع الإلكتروني', route: 'الاتجاهات', moreInfo: 'مزيد من المعلومات',
        openChat: 'افتح المحادثة', closeChat: 'أغلق المحادثة', clearChat: 'مسح المحادثة', clearInput: 'مسح', you: 'أنت', assistant: 'ستابي',
        disclaimer: 'هذا مساعد ذكاء اصطناعي. تحقق دائمًا من المعلومات المهمة مباشرة مع المؤسسة.',
        languageName: 'Arabic',
        aboutYouTitle: 'عنك (اختياري)', nameLabel: 'كيف نناديك؟', ageLabel: 'عمرك',
        genderLabel: 'جنسك', intakeNotStored: 'اختياري. لا يتم حفظه أبدًا.',
        loggingNotice: 'قد نستخدم هذه المحادثة لتحسين خدماتنا.',
        loggingOptOutLink: 'إلغاء الاشتراك لهذه الجلسة',
        loggingOptOutModalTitle: 'إيقاف تسجيل المحادثة؟',
        loggingOptOutModalBody: 'سيؤدي هذا إلى إيقاف حفظ هذه المحادثة للمراجعة، لبقية جلسة المتصفح هذه. يمكنك الاستمرار في الدردشة كالمعتاد.',
        loggingOptOutConfirm: 'إيقاف لهذه الجلسة',
        loggingOptOutCancel: 'إلغاء',
        loggingOptedOutNotice: 'تم إيقاف التسجيل لهذه الجلسة.',
    },
    tr: {
        title: 'Sorunuzu sorun', inputLabel: 'Sorunuzu yazın', send: 'Gönder',
        startHint: 'Bir konu seçin veya aşağıya bir soru yazın',
        thinking: 'Yanıtlanıyor…', error: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
        retry: 'Tekrar dene', relatedHelp: 'İlgili yardım',
        call: 'Ara', email: 'E-posta gönder', website: 'Web sitesi', route: 'Yol tarifi', moreInfo: 'Daha fazla bilgi',
        openChat: 'Sohbeti aç', closeChat: 'Sohbeti kapat', clearChat: 'Sohbeti temizle', clearInput: 'Temizle', you: 'Sen', assistant: 'Stappie',
        disclaimer: 'Bu bir yapay zeka asistanıdır. Önemli bilgileri her zaman kuruluşla doğrulayın.',
        languageName: 'Turkish',
        aboutYouTitle: 'Hakkında (isteğe bağlı)', nameLabel: 'Sana nasıl hitap edelim?', ageLabel: 'Yaşın',
        genderLabel: 'Cinsiyetin', intakeNotStored: 'İsteğe bağlı. Asla saklanmaz.',
        loggingNotice: 'Bu görüşmeyi hizmetlerimizi geliştirmek için kullanabiliriz.',
        loggingOptOutLink: 'Bu oturum için devre dışı bırak',
        loggingOptOutModalTitle: 'Görüşme kaydı kapatılsın mı?',
        loggingOptOutModalBody: 'Bu, bu tarayıcı oturumunun geri kalanında görüşmenin incelenmek üzere kaydedilmesini durdurur. Sohbete normal şekilde devam edebilirsin.',
        loggingOptOutConfirm: 'Bu oturum için kapat',
        loggingOptOutCancel: 'İptal',
        loggingOptedOutNotice: 'Bu oturum için kayıt kapatıldı.',
    },
    fr: {
        title: 'Posez votre question', inputLabel: 'Écrivez votre question', send: 'Envoyer',
        startHint: 'Choisissez un sujet ou posez une question ci-dessous',
        thinking: 'Réponse en cours…', error: "Une erreur s'est produite. Veuillez réessayer.",
        retry: 'Réessayer', relatedHelp: 'Aide associée',
        call: 'Appeler', email: 'Envoyer un e-mail', website: 'Site web', route: 'Itinéraire', moreInfo: "Plus d'infos",
        openChat: 'Ouvrir le chat', closeChat: 'Fermer le chat', clearChat: 'Effacer la conversation', clearInput: 'Effacer', you: 'Vous', assistant: 'Stappie',
        disclaimer: "Ceci est un assistant IA. Vérifiez toujours les informations importantes auprès de l'organisation elle-même.",
        languageName: 'French',
        aboutYouTitle: 'À propos de vous (facultatif)', nameLabel: 'Comment devons-nous vous appeler ?', ageLabel: 'Votre âge',
        genderLabel: 'Votre genre', intakeNotStored: 'Facultatif. Jamais enregistré.',
        loggingNotice: 'Nous pouvons utiliser cette conversation pour améliorer nos services.',
        loggingOptOutLink: 'Se désinscrire pour cette session',
        loggingOptOutModalTitle: "Désactiver l'enregistrement de la conversation ?",
        loggingOptOutModalBody: "Cela empêchera l'enregistrement de cette conversation à des fins d'examen, pour le reste de cette session de navigateur. Vous pouvez continuer à discuter normalement.",
        loggingOptOutConfirm: 'Désactiver pour cette session',
        loggingOptOutCancel: 'Annuler',
        loggingOptedOutNotice: "L'enregistrement est désactivé pour cette session.",
    },
    de: {
        title: 'Stell deine Frage', inputLabel: 'Frage eingeben', send: 'Senden',
        startHint: 'Wähle ein Thema oder stelle unten eine Frage',
        thinking: 'Antwortet…', error: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
        retry: 'Erneut versuchen', relatedHelp: 'Verwandte Hilfe',
        call: 'Anrufen', email: 'E-Mail senden', website: 'Webseite', route: 'Route', moreInfo: 'Mehr Infos',
        openChat: 'Chat öffnen', closeChat: 'Chat schließen', clearChat: 'Chat löschen', clearInput: 'Löschen', you: 'Du', assistant: 'Stappie',
        disclaimer: 'Dies ist ein KI-Assistent. Überprüfe wichtige Informationen immer bei der Organisation selbst.',
        languageName: 'German',
        aboutYouTitle: 'Über dich (optional)', nameLabel: 'Wie dürfen wir dich nennen?', ageLabel: 'Dein Alter',
        genderLabel: 'Dein Geschlecht', intakeNotStored: 'Optional. Wird nie gespeichert.',
        loggingNotice: 'Wir können dieses Gespräch nutzen, um unsere Dienste zu verbessern.',
        loggingOptOutLink: 'Für diese Sitzung abmelden',
        loggingOptOutModalTitle: 'Gesprächsprotokollierung deaktivieren?',
        loggingOptOutModalBody: 'Dadurch wird dieses Gespräch für den Rest dieser Browsersitzung nicht mehr zur Überprüfung gespeichert. Du kannst den Chat ganz normal weiter nutzen.',
        loggingOptOutConfirm: 'Für diese Sitzung deaktivieren',
        loggingOptOutCancel: 'Abbrechen',
        loggingOptedOutNotice: 'Die Protokollierung ist für diese Sitzung deaktiviert.',
    },
    es: {
        title: 'Haz tu pregunta', inputLabel: 'Escribe tu pregunta', send: 'Enviar',
        startHint: 'Elige un tema o haz una pregunta abajo',
        thinking: 'Pensando…', error: 'Algo salió mal. Inténtalo de nuevo.',
        retry: 'Intentar de nuevo', relatedHelp: 'Ayuda relacionada',
        call: 'Llamar', email: 'Enviar correo', website: 'Sitio web', route: 'Cómo llegar', moreInfo: 'Más información',
        openChat: 'Abrir chat', closeChat: 'Cerrar chat', clearChat: 'Borrar chat', clearInput: 'Borrar', you: 'Tú', assistant: 'Stappie',
        disclaimer: 'Esto es un asistente de IA. Verifica siempre la información importante con la organización misma.',
        languageName: 'Spanish',
        aboutYouTitle: 'Sobre ti (opcional)', nameLabel: '¿Cómo quieres que te llamemos?', ageLabel: 'Tu edad',
        genderLabel: 'Tu género', intakeNotStored: 'Opcional. Nunca se guarda.',
        loggingNotice: 'Podemos usar esta conversación para mejorar nuestros servicios.',
        loggingOptOutLink: 'Darse de baja para esta sesión',
        loggingOptOutModalTitle: '¿Desactivar el registro de la conversación?',
        loggingOptOutModalBody: 'Esto evitará que guardemos esta conversación para revisión durante el resto de esta sesión del navegador. Puedes seguir chateando con normalidad.',
        loggingOptOutConfirm: 'Desactivar para esta sesión',
        loggingOptOutCancel: 'Cancelar',
        loggingOptedOutNotice: 'El registro está desactivado para esta sesión.',
    },
    pt: {
        title: 'Faça a sua pergunta', inputLabel: 'Escreva a sua pergunta', send: 'Enviar',
        startHint: 'Escolha um tópico ou faça uma pergunta abaixo',
        thinking: 'A responder…', error: 'Algo correu mal. Tente novamente.',
        retry: 'Tentar novamente', relatedHelp: 'Ajuda relacionada',
        call: 'Ligar', email: 'Enviar e-mail', website: 'Sítio web', route: 'Direções', moreInfo: 'Mais informação',
        openChat: 'Abrir chat', closeChat: 'Fechar chat', clearChat: 'Limpar chat', clearInput: 'Limpar', you: 'Você', assistant: 'Stappie',
        disclaimer: 'Isto é um assistente de IA. Verifique sempre as informações importantes diretamente com a organização.',
        languageName: 'Portuguese',
        aboutYouTitle: 'Sobre você (opcional)', nameLabel: 'Como podemos chamá-lo(a)?', ageLabel: 'A sua idade',
        genderLabel: 'O seu género', intakeNotStored: 'Opcional. Nunca é guardado.',
        loggingNotice: 'Podemos utilizar esta conversa para melhorar os nossos serviços.',
        loggingOptOutLink: 'Cancelar para esta sessão',
        loggingOptOutModalTitle: 'Desativar o registo da conversa?',
        loggingOptOutModalBody: 'Isto impede que guardemos esta conversa para revisão, durante o resto desta sessão do navegador. Pode continuar a conversar normalmente.',
        loggingOptOutConfirm: 'Desativar para esta sessão',
        loggingOptOutCancel: 'Cancelar',
        loggingOptedOutNotice: 'O registo está desativado para esta sessão.',
    },
    pl: {
        title: 'Zadaj pytanie', inputLabel: 'Wpisz swoje pytanie', send: 'Wyślij',
        startHint: 'Wybierz temat lub zadaj pytanie poniżej',
        thinking: 'Odpowiadam…', error: 'Coś poszło nie tak. Spróbuj ponownie.',
        retry: 'Spróbuj ponownie', relatedHelp: 'Powiązana pomoc',
        call: 'Zadzwoń', email: 'Wyślij e-mail', website: 'Strona internetowa', route: 'Wskazówki dojazdu', moreInfo: 'Więcej informacji',
        openChat: 'Otwórz czat', closeChat: 'Zamknij czat', clearChat: 'Wyczyść czat', clearInput: 'Wyczyść', you: 'Ty', assistant: 'Stappie',
        disclaimer: 'To jest asystent AI. Zawsze sprawdzaj ważne informacje bezpośrednio w organizacji.',
        languageName: 'Polish',
        aboutYouTitle: 'O tobie (opcjonalnie)', nameLabel: 'Jak mamy się do ciebie zwracać?', ageLabel: 'Twój wiek',
        genderLabel: 'Twoja płeć', intakeNotStored: 'Opcjonalne. Nigdy nie zapisywane.',
        loggingNotice: 'Możemy wykorzystać tę rozmowę do ulepszenia naszych usług.',
        loggingOptOutLink: 'Zrezygnuj na tę sesję',
        loggingOptOutModalTitle: 'Wyłączyć zapisywanie rozmowy?',
        loggingOptOutModalBody: 'Spowoduje to zaprzestanie zapisywania tej rozmowy do przeglądu przez resztę tej sesji przeglądarki. Możesz normalnie kontynuować czat.',
        loggingOptOutConfirm: 'Wyłącz na tę sesję',
        loggingOptOutCancel: 'Anuluj',
        loggingOptedOutNotice: 'Zapisywanie jest wyłączone na tę sesję.',
    },
    ru: {
        title: 'Задайте свой вопрос', inputLabel: 'Введите свой вопрос', send: 'Отправить',
        startHint: 'Выберите тему или задайте вопрос ниже',
        thinking: 'Печатает…', error: 'Что-то пошло не так. Попробуйте ещё раз.',
        retry: 'Попробовать снова', relatedHelp: 'Похожая помощь',
        call: 'Позвонить', email: 'Написать', website: 'Веб-сайт', route: 'Маршрут', moreInfo: 'Подробнее',
        openChat: 'Открыть чат', closeChat: 'Закрыть чат', clearChat: 'Очистить чат', clearInput: 'Очистить', you: 'Вы', assistant: 'Stappie',
        disclaimer: 'Это ИИ-ассистент. Всегда уточняйте важную информацию непосредственно в организации.',
        languageName: 'Russian',
        aboutYouTitle: 'О вас (необязательно)', nameLabel: 'Как к вам обращаться?', ageLabel: 'Ваш возраст',
        genderLabel: 'Ваш пол', intakeNotStored: 'Необязательно. Никогда не сохраняется.',
        loggingNotice: 'Мы можем использовать этот разговор для улучшения наших услуг.',
        loggingOptOutLink: 'Отказаться на эту сессию',
        loggingOptOutModalTitle: 'Отключить сохранение разговора?',
        loggingOptOutModalBody: 'Это остановит сохранение этого разговора для проверки на оставшуюся часть этой сессии браузера. Вы можете продолжать общаться в обычном режиме.',
        loggingOptOutConfirm: 'Отключить для этой сессии',
        loggingOptOutCancel: 'Отмена',
        loggingOptedOutNotice: 'Сохранение отключено для этой сессии.',
    },
    zh: {
        title: '提出您的问题', inputLabel: '输入您的问题', send: '发送',
        startHint: '选择一个主题，或在下方提问',
        thinking: '正在回答…', error: '出了点问题，请重试。',
        retry: '重试', relatedHelp: '相关帮助',
        call: '致电', email: '发送邮件', website: '网站', route: '路线', moreInfo: '更多信息',
        openChat: '打开聊天', closeChat: '关闭聊天', clearChat: '清除聊天', clearInput: '清除', you: '你', assistant: 'Stappie',
        disclaimer: '这是一个人工智能助手。请务必直接向该机构核实重要信息。',
        languageName: 'Chinese',
        aboutYouTitle: '关于你（可选）', nameLabel: '我们该怎么称呼你？', ageLabel: '你的年龄',
        genderLabel: '你的性别', intakeNotStored: '可选。绝不会被保存。',
        loggingNotice: '我们可能会使用此对话来改进我们的服务。',
        loggingOptOutLink: '本次会话退出',
        loggingOptOutModalTitle: '关闭对话记录？',
        loggingOptOutModalBody: '这将在本次浏览器会话的剩余时间内停止保存此对话以供审核。您仍然可以正常聊天。',
        loggingOptOutConfirm: '本次会话关闭',
        loggingOptOutCancel: '取消',
        loggingOptedOutNotice: '本次会话记录已关闭。',
    },
};
