// Per-language UI chrome strings for ChatInterface — single source of truth shared
// between mini_site's ChatWidget.astro (the 11 real site languages) and admin_client's
// AiChatPreview.jsx (the CMS live preview, which follows the page editor's own
// "Bewerkingstaal" language picker). Previously each consumer kept its own copy —
// mini_site's stayed correct, admin_client's was a single hardcoded Dutch table, so the
// CMS preview never matched the language actually selected. Centralizing here means
// both stay in sync automatically instead of drifting again.
export const CHAT_STRINGS = {
    nl: {
        title: 'Stel je vraag', inputLabel: 'Typ je vraag', send: 'Verstuur',
        startHint: 'Kies een onderwerp of stel een vraag hieronder',
        thinking: 'Aan het antwoorden…', error: 'Er ging iets mis. Probeer het opnieuw.',
        retry: 'Opnieuw proberen', relatedHelp: 'Gerelateerde hulp',
        call: 'Bellen', email: 'E-mailen', website: 'Website', route: 'Route', moreInfo: 'Meer info',
        openChat: 'Open chat', closeChat: 'Sluit chat', clearChat: 'Wis chat', clearInput: 'Wissen', you: 'Jij', assistant: 'Stappie',
        disclaimer: 'Dit is een AI-assistent. Controleer belangrijke informatie altijd bij de organisatie zelf.',
        languageName: 'Dutch',
        aboutYouTitle: 'Over jou (optioneel)', nameLabel: 'Hoe mogen we je noemen?', ageLabel: 'Wat is je leeftijd?',
        genderLabel: 'Wat is je geslacht?', intakeNotStored: 'Optioneel. Wordt niet opgeslagen.',
    },
    en: {
        title: 'Ask your question', inputLabel: 'Type your question', send: 'Send',
        startHint: 'Choose a topic or ask a question below',
        thinking: 'Thinking…', error: 'Something went wrong. Please try again.',
        retry: 'Try again', relatedHelp: 'Related help',
        call: 'Call', email: 'Email', website: 'Website', route: 'Directions', moreInfo: 'More info',
        openChat: 'Open chat', closeChat: 'Close chat', clearChat: 'Clear chat', clearInput: 'Clear', you: 'You', assistant: 'Stappie',
        disclaimer: 'This is an AI assistant. Always double-check important details with the organisation itself.',
        languageName: 'English',
        aboutYouTitle: 'About you (optional)', nameLabel: 'What should we call you?', ageLabel: 'Your age',
        genderLabel: 'Your gender', intakeNotStored: 'Optional. Never stored.',
    },
    ar: {
        title: 'اطرح سؤالك', inputLabel: 'اكتب سؤالك', send: 'إرسال',
        startHint: 'اختر موضوعًا أو اطرح سؤالاً أدناه',
        thinking: 'جارٍ الكتابة…', error: 'حدث خطأ ما. حاول مرة أخرى.',
        retry: 'حاول مرة أخرى', relatedHelp: 'مساعدة ذات صلة',
        call: 'اتصال', email: 'بريد إلكتروني', website: 'الموقع الإلكتروني', route: 'الاتجاهات', moreInfo: 'مزيد من المعلومات',
        openChat: 'افتح المحادثة', closeChat: 'أغلق المحادثة', clearChat: 'مسح المحادثة', clearInput: 'مسح', you: 'أنت', assistant: 'ستابي',
        disclaimer: 'هذا مساعد ذكاء اصطناعي. تحقق دائمًا من المعلومات المهمة مباشرة مع المؤسسة.',
        languageName: 'Arabic',
        aboutYouTitle: 'عنك (اختياري)', nameLabel: 'كيف نناديك؟', ageLabel: 'عمرك',
        genderLabel: 'جنسك', intakeNotStored: 'اختياري. لا يتم حفظه أبدًا.',
    },
    tr: {
        title: 'Sorunuzu sorun', inputLabel: 'Sorunuzu yazın', send: 'Gönder',
        startHint: 'Bir konu seçin veya aşağıya bir soru yazın',
        thinking: 'Yanıtlanıyor…', error: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
        retry: 'Tekrar dene', relatedHelp: 'İlgili yardım',
        call: 'Ara', email: 'E-posta gönder', website: 'Web sitesi', route: 'Yol tarifi', moreInfo: 'Daha fazla bilgi',
        openChat: 'Sohbeti aç', closeChat: 'Sohbeti kapat', clearChat: 'Sohbeti temizle', clearInput: 'Temizle', you: 'Sen', assistant: 'Stappie',
        disclaimer: 'Bu bir yapay zeka asistanıdır. Önemli bilgileri her zaman kuruluşla doğrulayın.',
        languageName: 'Turkish',
        aboutYouTitle: 'Hakkında (isteğe bağlı)', nameLabel: 'Sana nasıl hitap edelim?', ageLabel: 'Yaşın',
        genderLabel: 'Cinsiyetin', intakeNotStored: 'İsteğe bağlı. Asla saklanmaz.',
    },
    fr: {
        title: 'Posez votre question', inputLabel: 'Écrivez votre question', send: 'Envoyer',
        startHint: 'Choisissez un sujet ou posez une question ci-dessous',
        thinking: 'Réponse en cours…', error: "Une erreur s'est produite. Veuillez réessayer.",
        retry: 'Réessayer', relatedHelp: 'Aide associée',
        call: 'Appeler', email: 'Envoyer un e-mail', website: 'Site web', route: 'Itinéraire', moreInfo: "Plus d'infos",
        openChat: 'Ouvrir le chat', closeChat: 'Fermer le chat', clearChat: 'Effacer la conversation', clearInput: 'Effacer', you: 'Vous', assistant: 'Stappie',
        disclaimer: "Ceci est un assistant IA. Vérifiez toujours les informations importantes auprès de l'organisation elle-même.",
        languageName: 'French',
        aboutYouTitle: 'À propos de vous (facultatif)', nameLabel: 'Comment devons-nous vous appeler ?', ageLabel: 'Votre âge',
        genderLabel: 'Votre genre', intakeNotStored: 'Facultatif. Jamais enregistré.',
    },
    de: {
        title: 'Stell deine Frage', inputLabel: 'Frage eingeben', send: 'Senden',
        startHint: 'Wähle ein Thema oder stelle unten eine Frage',
        thinking: 'Antwortet…', error: 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
        retry: 'Erneut versuchen', relatedHelp: 'Verwandte Hilfe',
        call: 'Anrufen', email: 'E-Mail senden', website: 'Webseite', route: 'Route', moreInfo: 'Mehr Infos',
        openChat: 'Chat öffnen', closeChat: 'Chat schließen', clearChat: 'Chat löschen', clearInput: 'Löschen', you: 'Du', assistant: 'Stappie',
        disclaimer: 'Dies ist ein KI-Assistent. Überprüfe wichtige Informationen immer bei der Organisation selbst.',
        languageName: 'German',
        aboutYouTitle: 'Über dich (optional)', nameLabel: 'Wie dürfen wir dich nennen?', ageLabel: 'Dein Alter',
        genderLabel: 'Dein Geschlecht', intakeNotStored: 'Optional. Wird nie gespeichert.',
    },
    es: {
        title: 'Haz tu pregunta', inputLabel: 'Escribe tu pregunta', send: 'Enviar',
        startHint: 'Elige un tema o haz una pregunta abajo',
        thinking: 'Pensando…', error: 'Algo salió mal. Inténtalo de nuevo.',
        retry: 'Intentar de nuevo', relatedHelp: 'Ayuda relacionada',
        call: 'Llamar', email: 'Enviar correo', website: 'Sitio web', route: 'Cómo llegar', moreInfo: 'Más información',
        openChat: 'Abrir chat', closeChat: 'Cerrar chat', clearChat: 'Borrar chat', clearInput: 'Borrar', you: 'Tú', assistant: 'Stappie',
        disclaimer: 'Esto es un asistente de IA. Verifica siempre la información importante con la organización misma.',
        languageName: 'Spanish',
        aboutYouTitle: 'Sobre ti (opcional)', nameLabel: '¿Cómo quieres que te llamemos?', ageLabel: 'Tu edad',
        genderLabel: 'Tu género', intakeNotStored: 'Opcional. Nunca se guarda.',
    },
    pt: {
        title: 'Faça a sua pergunta', inputLabel: 'Escreva a sua pergunta', send: 'Enviar',
        startHint: 'Escolha um tópico ou faça uma pergunta abaixo',
        thinking: 'A responder…', error: 'Algo correu mal. Tente novamente.',
        retry: 'Tentar novamente', relatedHelp: 'Ajuda relacionada',
        call: 'Ligar', email: 'Enviar e-mail', website: 'Sítio web', route: 'Direções', moreInfo: 'Mais informação',
        openChat: 'Abrir chat', closeChat: 'Fechar chat', clearChat: 'Limpar chat', clearInput: 'Limpar', you: 'Você', assistant: 'Stappie',
        disclaimer: 'Isto é um assistente de IA. Verifique sempre as informações importantes diretamente com a organização.',
        languageName: 'Portuguese',
        aboutYouTitle: 'Sobre você (opcional)', nameLabel: 'Como podemos chamá-lo(a)?', ageLabel: 'A sua idade',
        genderLabel: 'O seu género', intakeNotStored: 'Opcional. Nunca é guardado.',
    },
    pl: {
        title: 'Zadaj pytanie', inputLabel: 'Wpisz swoje pytanie', send: 'Wyślij',
        startHint: 'Wybierz temat lub zadaj pytanie poniżej',
        thinking: 'Odpowiadam…', error: 'Coś poszło nie tak. Spróbuj ponownie.',
        retry: 'Spróbuj ponownie', relatedHelp: 'Powiązana pomoc',
        call: 'Zadzwoń', email: 'Wyślij e-mail', website: 'Strona internetowa', route: 'Wskazówki dojazdu', moreInfo: 'Więcej informacji',
        openChat: 'Otwórz czat', closeChat: 'Zamknij czat', clearChat: 'Wyczyść czat', clearInput: 'Wyczyść', you: 'Ty', assistant: 'Stappie',
        disclaimer: 'To jest asystent AI. Zawsze sprawdzaj ważne informacje bezpośrednio w organizacji.',
        languageName: 'Polish',
        aboutYouTitle: 'O tobie (opcjonalnie)', nameLabel: 'Jak mamy się do ciebie zwracać?', ageLabel: 'Twój wiek',
        genderLabel: 'Twoja płeć', intakeNotStored: 'Opcjonalne. Nigdy nie zapisywane.',
    },
    ru: {
        title: 'Задайте свой вопрос', inputLabel: 'Введите свой вопрос', send: 'Отправить',
        startHint: 'Выберите тему или задайте вопрос ниже',
        thinking: 'Печатает…', error: 'Что-то пошло не так. Попробуйте ещё раз.',
        retry: 'Попробовать снова', relatedHelp: 'Похожая помощь',
        call: 'Позвонить', email: 'Написать', website: 'Веб-сайт', route: 'Маршрут', moreInfo: 'Подробнее',
        openChat: 'Открыть чат', closeChat: 'Закрыть чат', clearChat: 'Очистить чат', clearInput: 'Очистить', you: 'Вы', assistant: 'Stappie',
        disclaimer: 'Это ИИ-ассистент. Всегда уточняйте важную информацию непосредственно в организации.',
        languageName: 'Russian',
        aboutYouTitle: 'О вас (необязательно)', nameLabel: 'Как к вам обращаться?', ageLabel: 'Ваш возраст',
        genderLabel: 'Ваш пол', intakeNotStored: 'Необязательно. Никогда не сохраняется.',
    },
    zh: {
        title: '提出您的问题', inputLabel: '输入您的问题', send: '发送',
        startHint: '选择一个主题，或在下方提问',
        thinking: '正在回答…', error: '出了点问题，请重试。',
        retry: '重试', relatedHelp: '相关帮助',
        call: '致电', email: '发送邮件', website: '网站', route: '路线', moreInfo: '更多信息',
        openChat: '打开聊天', closeChat: '关闭聊天', clearChat: '清除聊天', clearInput: '清除', you: '你', assistant: 'Stappie',
        disclaimer: '这是一个人工智能助手。请务必直接向该机构核实重要信息。',
        languageName: 'Chinese',
        aboutYouTitle: '关于你（可选）', nameLabel: '我们该怎么称呼你？', ageLabel: '你的年龄',
        genderLabel: '你的性别', intakeNotStored: '可选。绝不会被保存。',
    },
};
